version: 8.0
os: linux

files:
   - source: /
     destination: /home/ubuntu/distribution
      
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu